DROP TABLE IF EXISTS user;
/*DROP TABLE IF EXISTS post;*/

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uname TEXT NOT NULL,
  ulast TEXT NOT NULL,
  email TEXT NOT NULL,
  birthday TEXT NOT NULL,
  addr TEXT NOT NULL,
  social TEXT NOT NULL,
  interest TEXT NOT NULL,
  music TEXT NOT NULL,
  voice_id,
  face_id
);

/*CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);*/